spring:
  application:
    name: dog-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/dog-db"
    username: "dog"
    password: "woof"
  jpa:
    open-in-view: false
  jmx:
    enabled: true
  sql:
    init:
      mode: always

server:
  error:
    include-message: always

management:
  observations:
    http:
      server:
        requests:
          name: "http.server.in"
  endpoints:
    web:
      exposure:
        include:
        - "*"
    jmx:
      exposure:
        include:
        - "*"
  endpoint:
    env:
      show-values: always

application:
  security:
    users:
    - name: "user"
      password: "password"
    - name: "admin"
      password: "secret"
      roles: ["admin"]
